### ISSUE TITLE
Getting error in Gradle 2.0 and Gradle-Wrapper 2.10 - Android Studio 2.0

### ISSUE THREAD

**Issue by vipulasri** [AppLozic/Applozic-Android-SDK#154]
I am getting errors in SDK after updating my App to Gradle 2.0 and Gradle-Wrapper 2.10

> ```
> Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
> Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$1) that doesn't come with an
> Error:associated EnclosingMethod attribute. This class was probably produced by a
> Error:compiler that did not target the modern .class file format. The recommended
> Error:solution is to recompile the class from source, using an up-to-date compiler
> Error:and without specifying any "-target" type options. The consequence of ignoring
> Error:this warning is that reflective operations on this class will incorrectly
> Error:indicate that it is *not* an inner class.
> Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
> Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$2) that doesn't come with an
> Error:associated EnclosingMethod attribute. This class was probably produced by a
> Error:compiler that did not target the modern .class file format. The recommended
> Error:solution is to recompile the class from source, using an up-to-date compiler
> Error:and without specifying any "-target" type options. The consequence of ignoring
> Error:this warning is that reflective operations on this class will incorrectly
> Error:indicate that it is *not* an inner class.
> ```

**Comment by vipulasri** [comment]
Got it resolved.
Just by updating the newer version of   `classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.1'` to `classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6'` in project **build.gradle**

**Comment by vipulasri** [comment]
Issue came back after cleaning up the project. :/

**Comment by eladnava** [comment]
Same issue here. Did you manage to find a solution, @vipulasri?

**Comment by eladnava** [comment]
I think I managed to find a weird solution -- manually building [mqttv3](https://github.com/eclipse/paho.mqtt.java/tree/master/org.eclipse.paho.client.mqttv3) and omitting the [resources](https://github.com/eclipse/paho.mqtt.java/tree/master/org.eclipse.paho.client.mqttv3/src/main/resources) folder completely might have worked around the bug for me.

I then had to modify [LoggerFactory](https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/logging/LoggerFactory.java) to not rely on `JSR47Logger.java` since that class relies on those resources which I omitted.

Complicated, but works.
