### ISSUE TITLE
Contact list is showing wrong user names while creating group

### ISSUE THREAD

**Issue by priyadarshi** [AppLozic/Applozic-Android-SDK#159]
Contact list is showing wrong user names while creating group
It shows userId,timestamp.

**Comment by devashishmamgain** [comment]
@priyadarshi @adarshmishra 
@adarshmishra can you send one apk to @priyadarshi for testing.

Steps to reproduce:
Send message from A to B.
Keep A in foreground. On B, go to background, now check on A's contact list.

**Comment by adarshmishra** [comment]
@priyadarshi Can you please test and see if issue is fixed?

**Comment by sunip123** [comment]
@devashishmamgain  I have reproduce the above steps for the Bug with the apk but not got such issue as above one.

**Comment by devashishmamgain** [comment]
It's fixed now, should not be happening any more. After the fix, I havnt
seen the issue, earlier I used to get this after every few days.
On 28 Apr 2016 7:35 p.m., "SUJIT SINGH" <notifications@github.com> wrote:

@devashishmamgain <https://github.com/devashishmamgain> I have reproduce
the above steps for the Bug with the apk but not got such issue as above
one.

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/AppLozic/Applozic-Android-SDK/issues/159#issuecomment-215433987>

**Comment by devashishmamgain** [comment]
Lets keep it open for few days, I am installing latest build to try it.
